module.exports = {
	FETCHING: 1
	,SCRUBBING: 2
	,DECAYING: 3
	,SCRUBBING_AND_DECAYING: 4
	,FETCHING_RAW: 5
	,INCREMENTING: 6
	,FILTERING_KEYS: 7
	,VALIDATING_INCREMENT_DATE: 8
	,UPDATING_DECAY_DATE: 9
	,FETCHING_LAST_DECAY_DATE: 10
	,FETCHING_LIFETIME_DATE: 11
};
